# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to build and deploy WebApp only - no bicep deploy
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: 3.build.deploy.app
run-name: '3 - Build & Deploy App: using ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        default: 'dev' 
        type: environment
      runSecurityScan:
        description: Run Security Scan
        default: false
        type: boolean
      runBuildDeploy:
        description: Build and Deploy App
        default: true
        type: boolean
      runSmokeTest:
        description: Run Smoke Tests
        default: false
        type: boolean
      logLevel:
        description: Log level
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read
  packages: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    if: inputs.runSecurityScan
    with:
      runMSDevSecOpsScan: ${{ inputs.runSecurityScan }}
      runGHASScan: false

  # ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build WebApp
    uses: ./.github/workflows/template-webapp-build.yml
    if: inputs.runBuildDeploy || inputs.runSmokeTest
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      rootDirectory: '${{ vars.APP_PROJECT_FOLDER_NAME }}'
      projectName: '${{ vars.APP_PROJECT_NAME }}'
      testDirectory: '${{ vars.APP_TEST_FOLDER_NAME }}'
      testProjectName: '${{ vars.APP_TEST_PROJECT_NAME }}'
      testApplication: true
      listFilesAfterBuild: true

# ------------------------------------------------------------------------------------------------------------------------
  deploy-app:
    name: Deploy WebApp ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-webapp-deploy.yml
    if: inputs.runBuildDeploy || inputs.runSmokeTest
    needs: build-app
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}

      
# ------------------------------------------------------------------------------------------------------------------------
  run-smoke-test:
    name: Smoke Test ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-smoke-test.yml
    if: inputs.runSmokeTest
    needs: deploy-app
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      testPath: 'playwright/ui-tests'
      testType: 'ui'
